### ISSUE TITLE
Newest Firmware for z9v5 pro - extruder now runs backwards

### ISSUE THREAD

**Issue by wf5w** [ZONESTAR3D/Firmware#6]
My son, who owns a Zonestar 3D z9v5 pro, says that the newest firmware makes his extruder run backwards.
That is all I know.

Has anyone else seen this issue?

If so, is there a fix?

**Comment by ZONESTAR3D** [comment]
Hello,
Please pay attention to distinguishing product models, MK1/MK2/MK3/MK4 uses different firmware

**Comment by Santilich83** [comment]
Same problem. Post the normal firmware for Z9V5PRO MK5 without inverting the extruder motor control.

**Comment by ZONESTAR3D** [comment]
If you upload firmware of Z9V5Pro-MK4/MK5 and the extruder work direction is reversed, that means your printer model is Z9V5Pro-MK1 or MK2. please download the firmware from here:
https://github.com/ZONESTAR3D/Firmware/tree/master/Z9/Z9V5/bin/Z9V5Pro

For the differences between MK1/MK2/MK3/MK4MK5 please check here:
[https://github.com/ZONESTAR3D/Firmware/tree/master/Z9/Z9V5/bin#bulb -How do i know if my machine is mk1-mk2-mk3-or-mk4](https://github.com/ZONESTAR3D/Z9/tree/main/Z9V5#whats-different-on-z9v5-mk1mk2mk3mk4mk5)
